ERPApplication/Controllers/SupplierController.cs
using ERPApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ERPApplication.Controllers
{
    public class SupplierController : Controller
    {
        private ERPContext _context;

        public SupplierController()
        {
            _context = new ERPContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET: Supplier
        public ActionResult Index()
        {
            var suppliers = _context.Suppliers.ToList();
            return View(suppliers);
        }

        public ActionResult New()
        {
            return View("SupplierForm");
        }

        [HttpPost]
        public ActionResult Save(Supplier supplier)
        {
            if(supplier.SupplierId == 0)
            {
                _context.Suppliers.Add(supplier);
            }
            else
            {
                var supplierInDB = _context.Suppliers.Single(s => s.SupplierId == supplier.SupplierId);
                supplierInDB.CompanyName = supplier.CompanyName;
                supplierInDB.ContactName = supplier.ContactName;
                supplierInDB.ContactTitle = supplier.ContactTitle;
                supplierInDB.City = supplier.City;
                supplierInDB.Country = supplier.Country;
                supplierInDB.Phone = supplier.Phone;
                supplierInDB.Fax = supplier.Fax;
            }
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var supplierInDB = _context.Suppliers.Single(s => s.SupplierId == id);

            if (supplierInDB == null)
                return HttpNotFound();

            return View("SupplierForm", supplierInDB);
        }

        public ActionResult Details(int id)
        {
            var supplierInDB = _context.Suppliers.Single(s => s.SupplierId == id);

            if (supplierInDB == null)
                return HttpNotFound();

            return View(supplierInDB);
        }

        public ActionResult Delete(int id)
        {
            var supplierInDB = _context.Suppliers.Single(s => s.SupplierId == id);

            if (supplierInDB == null)
                return HttpNotFound();

            return View(supplierInDB);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var supplierInDB = _context.Suppliers.Single(s => s.SupplierId == id);

            if (supplierInDB == null)
                return HttpNotFound();

            _context.Suppliers.Remove(supplierInDB);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ERPApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-fixed-top navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Customers", "Index", "Customer")</li>
                    <li>@Html.ActionLink("Suppliers", "Index", "Supplier")</li>
                    <li>@Html.ActionLink("Products", "Index", "Product")</li>
                    <li>@Html.ActionLink("Orders", "Index", "Order")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>